### ISSUE TITLE
Count totals pushed to second line in FF/Safari for Mac

### ISSUE THREAD

**Issue by nutsandbolts** [warfare-plugins/social-warfare#226]
Ticket is here: iref: 5116

In Safari and Firefox for Mac, the share count total gets pushed onto a second line even when the browser window is enormous. Seems to be fine in Chrome.

**Comment by Nicholas-Cardot** [comment]
Dustin and I have been unable to replicate this issue. Are we sure the user is on the latest version of Social Warfare?

**Comment by nutsandbolts** [comment]
Yep, I've seen it on a couple of tickets. Maybe a plugin conflict of some sort?

**Comment by Nicholas-Cardot** [comment]
Actually, I wonder if maybe it was related to a minification issue that i just fixed. I changed our in-house minification method for script.min.js and it seems to have already fixed a couple of issues on the current version. Let's give this newest version a test and see if it fixed this one also.

**Comment by nutsandbolts** [comment]
@Nicholas-Cardot still seeing this on some sites (see iref 5251) - I see it in Chrome on this site when hovering over the Tweet button, but only if I resize my browser to just before the breakpoint where the total doesn't display.

**Comment by adamhagerman** [comment]
@Nicholas-Cardot @nutsandbolts Has there been any updates to this issue? Here's an image of the issue in Chrome:

![screenshot 2016-10-01 16 23 20](https://cloud.githubusercontent.com/assets/22566308/19016830/7a93d3e2-87f3-11e6-9ab6-0c842ef4152b.png)

If I shrink the page size and then maximize it again, the issue corrects itself. But if I go to a separate page it does it again.

**Comment by Nicholas-Cardot** [comment]
This should be fully resolved in the 2.1.0 release.
