### ISSUE TITLE
Banner Occludes Settings

### ISSUE THREAD

**Issue by VR51** [warfare-plugins/social-warfare#408]
The SW Pro banner in the settings page overlays above the settings.

The image is within CSS class .sw-grid that uses 'position: fixed'. It needs to be 'position:relative' with 'left:0'.

Try this instead:

```
.sw-grid {
  position: relative!important;
  left:0!important;
}
```

You probably won't need the !important flag.

**Comment by VR51** [comment]
The problem persists into 2.3.1.

**Comment by Nicholas-Cardot** [comment]
All our testing shows that this is fixed. It most likely means that you need to clear caching plugins to let the new CSS through.

**Comment by VR51** [comment]
Partly correct. Hadn't realised my browser had cached the admin area.

With all caches wiped (site, CDN and browser) I still see that the banner remains fixed to the page top at about 77.5px lower than the viewport edge (internal). Not an issue now for me because the banner is shorter than it was yesterday (being menu sized) but could be an issue on smaller screens.

**Comment by DustinWStout** [comment]
This has been fixed in version 2.3.1.
